<?php

namespace App\Services;

use App\Models\SiteSetting;
use Illuminate\Support\Facades\File;
use Symfony\Component\Yaml\Yaml;

class TraefikConfigService
{
    /**
     * Synchronize and write dynamic Traefik routes for Control Plane based on Site Settings.
     */
    public static function syncControlPlaneRoutes(): string
    {
        $instanceUrl = SiteSetting::get('instance_url', env('APP_URL', 'http://localhost'));
        $wildcardDomain = SiteSetting::get('wildcard_domain', '*.dyzulk.test');

        $hostRules = [
            'Host(`localhost`)',
            'Host(`127.0.0.1`)',
            'Host(`office.localhost`)',
        ];

        // Parse host from instance_url
        $parsedHost = parse_url($instanceUrl, PHP_URL_HOST);
        if ($parsedHost) {
            $hostRules[] = "Host(`{$parsedHost}`)";
            $hostRules[] = "Host(`office.{$parsedHost}`)";
            $hostRules[] = "Host(`api.{$parsedHost}`)";
        }

        $publicIp = SiteSetting::get('public_ipv4');
        if ($publicIp) {
            $hostRules[] = "Host(`{$publicIp}`)";
        }

        // Deduplicate host rules
        $hostRules = array_unique(array_values($hostRules));
        $ruleString = implode(' || ', $hostRules);

        $targetServiceHost = env('TRAEFIK_TARGET_SERVICE', 'dyzulk-cloud-dev-app');

        $config = [
            'http' => [
                'routers' => [
                    'dyzulk-cloud-control-plane' => [
                        'entryPoints' => ['web'],
                        'rule' => $ruleString,
                        'service' => 'dyzulk-cloud-control-plane-service',
                    ],
                ],
                'services' => [
                    'dyzulk-cloud-control-plane-service' => [
                        'loadBalancer' => [
                            'servers' => [
                                ['url' => "http://{$targetServiceHost}:80"],
                            ],
                        ],
                    ],
                ],
            ],
        ];

        $yamlContent = "# Auto-generated by dyzulk-cloud Control Plane via Site Settings\n".
            "# Do not edit manually; changes will be overwritten.\n\n".
            Yaml::dump($config, 6, 2);

        // Destination paths
        $paths = [
            base_path('docker/traefik/dynamic/control-plane.yml'),
        ];

        if (File::exists('/data/dyzulk-cloud/proxy/dynamic')) {
            $paths[] = '/data/dyzulk-cloud/proxy/dynamic/control-plane.yml';
        }

        foreach ($paths as $path) {
            $dir = dirname($path);
            if (! File::exists($dir)) {
                File::makeDirectory($dir, 0755, true, true);
            }
            File::put($path, $yamlContent);
        }

        return $yamlContent;
    }
}
