name: dyzulk-cloud-dev

services:
    laravel.test:
        build:
            context: './docker/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: 'dyzulk-cloud-dev-app:latest'
        container_name: dyzulk-cloud-dev-app
        labels:
            com.dyzulk.environment: 'development'
            com.dyzulk.service: 'sail'
            com.dyzulk.app: 'dyzulk-cloud'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:8000'
            - '${OFFICE_PORT:-8001}:8001'
            - '${API_PORT:-8002}:8002'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        volumes:
            - '.:/var/www/html'
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - sail-dev

    traefik:
        image: 'traefik:v3.0'
        container_name: dyzulk-cloud-dev-ingress
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--providers.file.directory=/etc/traefik/dynamic'
            - '--providers.file.watch=true'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'
        environment:
            DOCKER_API_VERSION: "1.40"
        ports:
            - '${TRAEFIK_HTTP_PORT:-80}:80'
            - '${TRAEFIK_HTTPS_PORT:-443}:443'
            - '${TRAEFIK_DASHBOARD_PORT:-8080}:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './docker/traefik/dynamic:/etc/traefik/dynamic'
        networks:
            - sail-dev

networks:
    sail-dev:
        driver: bridge
