<?php

namespace App\Services\Traefik;

use App\Models\SiteSetting;
use Illuminate\Support\Facades\File;
use Symfony\Component\Yaml\Yaml;

class TraefikConfigService
{
    /**
     * Determine if a domain value is a valid external domain (not localhost/empty).
     */
    private static function isExternalDomain(?string $domain): bool
    {
        if (empty($domain)) {
            return false;
        }

        return ! in_array(strtolower($domain), ['localhost', '127.0.0.1']);
    }

    /**
     * Synchronize and write dynamic Traefik routes for Control Plane based on Site Settings.
     *
     * Traefik ONLY handles external domain routing on Port 80 (web) and Port 443 (websecure).
     * Ports 8000, 8001, and 8002 are exposed directly from the Laravel container
     * and never pass through Traefik.
     */
    public static function syncControlPlaneRoutes(): string
    {
        $appDomain = SiteSetting::get('app_domain', 'localhost');
        $officeDomain = SiteSetting::get('office_domain', 'localhost');
        $apiDomain = SiteSetting::get('api_domain', 'localhost');

        $targetServiceHost = env('TRAEFIK_TARGET_SERVICE', 'dyzulk-cloud-dev-app');

        $routers = [];
        $services = [];

        /** @var array{name: string, domain: string, port: int} $mapping */
        $mappings = [
            ['name' => 'app', 'domain' => $appDomain, 'port' => 8000],
            ['name' => 'office', 'domain' => $officeDomain, 'port' => 8001],
            ['name' => 'api', 'domain' => $apiDomain, 'port' => 8002],
        ];

        foreach ($mappings as $mapping) {
            if (! self::isExternalDomain($mapping['domain'])) {
                continue;
            }

            $routerName = "dyzulk-cloud-{$mapping['name']}";
            $serviceName = "dyzulk-cloud-{$mapping['name']}-service";

            $routers[$routerName] = [
                'entryPoints' => ['web', 'websecure'],
                'rule' => "Host(`{$mapping['domain']}`)",
                'service' => $serviceName,
            ];

            $services[$serviceName] = [
                'loadBalancer' => [
                    'servers' => [
                        ['url' => "http://{$targetServiceHost}:{$mapping['port']}"],
                    ],
                ],
            ];
        }

        $config = [
            'http' => [
                'routers' => $routers ?: null,
                'services' => $services ?: null,
            ],
        ];

        // Remove null keys for clean YAML output
        $config['http'] = array_filter($config['http']);

        $yamlContent = "# Auto-generated by dyzulk-cloud Control Plane via Site Settings\n".
            "# Do not edit manually; changes will be overwritten.\n".
            "# Traefik handles ONLY external domain routing on Port 80/443.\n".
            "# Ports 8000, 8001, 8002 bypass Traefik entirely (direct container access).\n\n".
            Yaml::dump($config, 6, 2);

        // Destination paths
        $paths = [
            base_path('docker/traefik/dynamic/control-plane.yml'),
        ];

        if (File::exists('/data/dyzulk-cloud/proxy/dynamic')) {
            $paths[] = '/data/dyzulk-cloud/proxy/dynamic/control-plane.yml';
        }

        foreach ($paths as $path) {
            $dir = dirname($path);
            if (! File::exists($dir)) {
                File::makeDirectory($dir, 0755, true, true);
            }
            File::put($path, $yamlContent);
        }

        return $yamlContent;
    }
}
