<?php

namespace App\Services\Traefik;

use App\Models\SiteSetting;
use Illuminate\Support\Facades\File;
use Symfony\Component\Yaml\Yaml;

class TraefikConfigService
{
    /**
     * Synchronize and write dynamic Traefik routes for Control Plane based on Site Settings.
     */
    public static function syncControlPlaneRoutes(): string
    {
        $instanceUrl = SiteSetting::get('instance_url', env('APP_URL', 'http://localhost'));
        $wildcardDomain = SiteSetting::get('wildcard_domain', '*.dyzulk.test');

        $appDomain = SiteSetting::get('app_domain', 'localhost');
        $officeDomain = SiteSetting::get('office_domain', 'localhost');
        $apiDomain = SiteSetting::get('api_domain', 'localhost');

        $targetServiceHost = env('TRAEFIK_TARGET_SERVICE', 'dyzulk-cloud-dev-app');

        $appHosts = array_values(array_filter(array_unique([$appDomain, 'localhost', '127.0.0.1'])));
        $appRule = implode(' || ', array_map(fn ($host) => "Host(`{$host}`)", $appHosts));

        $officeHosts = array_values(array_filter(array_unique([$officeDomain, 'localhost', '127.0.0.1'])));
        $officeRule = implode(' || ', array_map(fn ($host) => "Host(`{$host}`)", $officeHosts));

        $apiHosts = array_values(array_filter(array_unique([$apiDomain, 'localhost', '127.0.0.1'])));
        $apiRule = implode(' || ', array_map(fn ($host) => "Host(`{$host}`)", $apiHosts));

        $config = [
            'http' => [
                'routers' => [
                    'dyzulk-cloud-app' => [
                        'entryPoints' => ['web', 'app'],
                        'rule' => $appRule,
                        'service' => 'dyzulk-cloud-control-plane-service',
                    ],
                    'dyzulk-cloud-office' => [
                        'entryPoints' => ['office'],
                        'rule' => $officeRule,
                        'service' => 'dyzulk-cloud-control-plane-service',
                    ],
                    'dyzulk-cloud-api' => [
                        'entryPoints' => ['api'],
                        'rule' => $apiRule,
                        'service' => 'dyzulk-cloud-control-plane-service',
                    ],
                ],
                'services' => [
                    'dyzulk-cloud-control-plane-service' => [
                        'loadBalancer' => [
                            'servers' => [
                                ['url' => "http://{$targetServiceHost}:80"],
                            ],
                        ],
                    ],
                ],
            ],
        ];

        $yamlContent = "# Auto-generated by dyzulk-cloud Control Plane via Site Settings\n".
            "# Do not edit manually; changes will be overwritten.\n\n".
            Yaml::dump($config, 6, 2);

        // Destination paths
        $paths = [
            base_path('docker/traefik/dynamic/control-plane.yml'),
        ];

        if (File::exists('/data/dyzulk-cloud/proxy/dynamic')) {
            $paths[] = '/data/dyzulk-cloud/proxy/dynamic/control-plane.yml';
        }

        foreach ($paths as $path) {
            $dir = dirname($path);
            if (! File::exists($dir)) {
                File::makeDirectory($dir, 0755, true, true);
            }
            File::put($path, $yamlContent);
        }

        return $yamlContent;
    }
}
